### ISSUE TITLE
Kurulum Hakkında

### ISSUE THREAD

**Issue by onuryildirimm** [ozgur-soft/posnet#1]
Merhaba,
Başka bankaların php sanal poslarını kullanıyorum. Bu projenin normal bir hostta kullanımı mümkün mü ? Ayrıca kurulum için ek ne yapılması gerek bilgi var mıdır ?

**Comment by OzqurYalcin** [comment]
api​ ​:=​ ​&​posnet.​API​{​"test"​} satırı ile bankanın test ortamında çalışmaktadır.
Üretim ortamına geçildiğinde
api​ ​:=​ ​&​posnet.​API​{​"prod"​} olarak değişmeniz gerekiyor.
MerchantId ve TerminalId bilgilerini de kendi bilgilerinizle değişmeniz gerekiyor.

Bunun dışında php ile arasında çalışma mantığı olarak hiçbir fark yoktur.
Biz şuan halihazırda kullanmaktayız. Sorunsuz çalışmaktadır.

**Comment by onuryildirimm** [comment]
buradaki ayarları güncelleme konusunda sorunum yok. Detaylı olarak anlatmak gerekirse 3d_payment sayfasındaki bilgileri 3d_post sayfasına post ettirdiğimde herhangi bir sonuç alamıyorum. hazırlanan bu html sayfalarında herhangi bir include yok. Bağlantıyı posnet classı ile nasıl kurabilriz, örnek basit bir uygulama var mıdır diye sormak istemiştim.
